### ISSUE TITLE
Change output csv delimiter from tab to semicolon

### ISSUE THREAD

**Issue by goblinqueen** [goblinqueen/zenpal#1]
Script output is tab-separated now.
I'd love it to use ; as separator instead and I'm lazy.
You'll need to al least check it's not in the input fields

thanks!

**Comment by RiyaRiya** [comment]
I'll take this please!

**Comment by goblinqueen** [comment]
thanks, go ahead.

**Comment by RiyaRiya** [comment]
unclaiming since unable to test due to non existing transaction data in paypal account.

**Comment by goblinqueen** [comment]
Here's a test file for you @RiyaRiya

```
"Date","Time","TimeZone","Name","Type","Status","Currency","Amount","Receipt ID","Balance"
"13/10/2018","03:03:18","MSK","Google Payment Corporation","PreApproved Payment Bill User Payment","Completed","RUB","-379.00","","-679.00"
"13/10/2018","03:03:18","MSK","","General Currency Conversion","Completed","USD","-5.94","","33.95"
"13/10/2018","03:03:18","MSK","","General Currency Conversion","Completed","RUB","379.00","","-300.00"
```

**Comment by goblinqueen** [comment]
up for grabs again, I guess

**Comment by denis-zyk** [comment]
I'll take this

**Comment by goblinqueen** [comment]
@denis-zyk I've been informed the test csv does not work, a quick fix is to replace line 14 with ``` Date = 'Date' ``` for testing purposes (don't commit this change!)
I'm working on removing those nasty special symbols

**Comment by goblinqueen** [comment]
I've fixed the special symbol issue, you may wish to merge upstream

**Comment by denis-zyk** [comment]
Great, I have merged upstream and pushed my changes & PR-ed

**Comment by goblinqueen** [comment]
Thanks a lot
