### ISSUE TITLE
Change hardcoded input file to CLI param

### ISSUE THREAD

**Issue by goblinqueen** [goblinqueen/zenpal#3]
The script currently assumes there's a Download.CSV next to it because I'm lazy.
It should be a CLI param instead, like this:

``$ ./zenpal.py ~/Downloads/Download\ \(1\).CSV > result.csv``

Result in the STDOUT is fine, however, you may add an optional parameter for the output file.
There's no need to keep the default behaviour and you may approach it as you like, actually.

thanks!

**Comment by goblinqueen** [comment]
here's a test Download.CSV file in case you need it.
```
"Date","Time","TimeZone","Name","Type","Status","Currency","Amount","Receipt ID","Balance"
"13/10/2018","03:03:18","MSK","Google Payment Corporation","PreApproved Payment Bill User Payment","Completed","RUB","-379.00","","-679.00"
"13/10/2018","03:03:18","MSK","","General Currency Conversion","Completed","USD","-5.94","","33.95"
"13/10/2018","03:03:18","MSK","","General Currency Conversion","Completed","RUB","379.00","","-300.00"
```

**Comment by sudoursa** [comment]
I'll take this.

**Comment by goblinqueen** [comment]
thanks, have fun

**Comment by goblinqueen** [comment]
still not sure how this works

**Comment by goblinqueen** [comment]
argh

**Comment by goblinqueen** [comment]
whoah
